services:
  postgres:
    image: "postgres:15-alpine"
    container_name: "postgres_data"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order_network

  app:
    build: .
    container_name: 'order_service'
    ports:
      - '8082:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/database
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    networks:
      - order_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  order_network: